### ISSUE TITLE
EasyThreed K9 version

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [schmttc/EasyThreeD-K7-STM32#10]
I have an EasyThreed K9 with ET4000+ board, but it has a few differences. Some perfipherals are missing and wifi board connector is used by the front panel buttons. Would you be interested in making another repo for K9 if I provide photos and pin/button mappings?

**Comment by schmttc** [comment]
Hi, I have been thinking that it would make sense to have a central repo to manage the different device firmwares. 
I need to think about the best way to organise this to keep maintenace low, but happy to provide a branch you can PR to in the mean time? I don't have time at the moment to do any development work.

**Comment by JohnTheCoolingFan** [comment]
Yeah, both of thsoe are great ideas. I'll do what I can in the meantime. I was planning to mod my printer anyways. Thanks for the response!

**Comment by schmttc** [comment]
https://github.com/schmttc/EasyThreeD-K7-STM32/tree/ET4000PLUS-K9

I've put a few pointers in the README to get started, check the master branch READMA for additional details, and the Additional-Files branch for board schematics

**Comment by JohnTheCoolingFan** [comment]
Finally got to have a look. From what I can see, controls are mostly the same but I think the 4 front leveling buttons need to be added. I'll check the pins later. Also will take a better look at what STM32 model is installed in my printer.

**Comment by schmttc** [comment]
@JohnTheCoolingFan have you/can you email Easythreed support and ask for a copy of the source code for your printer? They were a bit hesitant for me but it would make the development work a lot easier.

**Comment by JohnTheCoolingFan** [comment]
That's an interesting suggestion. Probably worth a try.
I'm a bit concerned whethr this printer model is even real as it's not displayed at easythreed website.

**Comment by schmttc** [comment]
I was just thinking about this and remembered that all of the EasyThreed printers are all the same hardware in a different form factor; so you could try and  flash my K7 firmware and it might all just work, except for the homing buttons.
If it doesn't work, you can just flash back,I've flashed plenty of bad firmwares and always been able to roll back.
Try this one https://github.com/schmttc/EasyThreeD-K7-STM32/blob/backlashfix/mksLite.bin

**Comment by schmttc** [comment]
I've started creating the central repo to firmware for multiple printers, if you have any feedback please let me know https://github.com/EasyThreed-Community-Firmware/Marlin

**Comment by Ajimaru** [comment]
Which Firmware can I use for testing on a K9?

**Comment by JohnTheCoolingFan** [comment]
Are you asking for a compiled file @Ajimaru? I can compile it if you want.

**Comment by JohnTheCoolingFan** [comment]
Here you go, uploaded it to my web server: https://jtcf.ru/EasyThreed-K9-firmware/mksLite-c4def742.bin

**Comment by Ajimaru** [comment]
> Here you go, uploaded it to my web server: https://jtcf.ru/EasyThreed-K9-firmware/mksLite-c4def742.bin

I have installed this firmware via the sd-card.
```
Firmware Name: Marlin 2.1.2.1 (Mar 7 2024 22:21:12)
Extruder Count: 1
Machine Type: 3D Printer
Protocol Version: 1.0
Source Code Url: github.com/MarlinFirmware/Marlin
Uuid: cede2a2f-41a2-4748-9b12-c55c62f367ff 
``` 

Good news, headbet is working.
Bad news, the four bed leveling buttons and the home button on the printer does not work anymore.
COntroling via USB does not work either.
In addition all theese settings are on zero.
```
[Steps]
[Feedrate]
[Acceleration]
[Offsets]
[PID]
[Material]
[Linear Advance]
[Advanced]
```

**Comment by JohnTheCoolingFan** [comment]
That's weird. Can you open the printer and read a model of the board to make sure it is ET4000+?

Photos of the board and the extension board on the place of the wifi module would be nice for finding the culprit too.

**Comment by Ajimaru** [comment]
Yes the board is an ET4000+ , here are some pictures.

![IMG_7932](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/38381946/6decfcbb-1181-42f7-9807-7cd4e0aef633)
![IMG_7933](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/38381946/66c250e5-df1b-4f8e-8a44-31b431c8981c)
![IMG_7934](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/38381946/ddfd2f6a-b5e8-4f2e-8d27-4c07bb06e8ca)
![IMG_7935](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/38381946/b84d613c-b651-402d-8544-e033279807d7)
![IMG_7936](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/38381946/137e2219-3a76-4438-8122-c04e09697eed)


I have set the missing values according to [EasyThreed K9 Marlin factory firmware configuration ](https://gist.github.com/JohnTheCoolingFan/39227f4ddd12a7c614d4e360d0473e6a)

**M503** shows this, after powercylce of the printer, the values are back to zero.

```
echo:; Linear Units:
echo:  G21 ; (mm)
echo:; Temperature Units:
echo:  M149 C ; Units in Celsius
echo:; Filament settings (Disabled):
echo:  M200 S0 D0.00
echo:; Steps per unit:
echo:  M92 X606.00 Y606.00 Z600.00 E1040.00
echo:; Max feedrates (units/s):
echo:  M203 X40.00 Y40.00 Z10.00 E70.00
echo:; Max Acceleration (units/s2):
echo:  M201 X100.00 Y100.00 Z50.00 E100.00
echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
echo:  M204 P100.00 R100.00 T100.00
echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>):
echo:  M205 B0.00 S0.00 T0.00 J0.00
echo:; Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:; Hotend PID:
echo:  M301 P22.20 I1.08 D114.00
echo:; Linear Advance:
echo:  M900 K0.00
echo:; Stepper motor currents:
echo:  M907 X0 Z0 E0
echo:; Backlash compensation:
echo:  M425 F0.00 S0.00 X0.00 Y0.00 Z0.00
``` 

Still only nozzle and bed heating works, all functions related to motors are dead.
You have the stock firmware?

**Comment by JohnTheCoolingFan** [comment]
Yes, I have the stock firmware which I got from the manufacturer. I also uploaded it to my webserver: http://jtcf.ru/EasyThreed-K9-firmware/EasyThreed-K9-factory-firmware.bin

**Comment by JohnTheCoolingFan** [comment]
Your daughter board for the front levelling buttons looks different. Can you please use a multimeter to map the contacts on the daughter board on the front to the contacts on the board in the wifi module slot?
![pins_to_map](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/43478602/d8370af4-aeb5-42bc-817f-eececfeabd65)

**Comment by Ajimaru** [comment]
> Yes, I have the stock firmware which I got from the manufacturer. I also uploaded it to my webserver: http://jtcf.ru/EasyThreed-K9-firmware/EasyThreed-K9-factory-firmware.bin

The Printer is working again with the factory firmware!

**Comment by Ajimaru** [comment]
> Your daughter board for the front levelling buttons looks different. Can you please use a multimeter to map the contacts on the daughter board on the front to the contacts on the board in the wifi module slot? ![pins_to_map](https://private-user-images.githubusercontent.com/43478602/311383241-d8370af4-aeb5-42bc-817f-eececfeabd65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODAxMjksIm5iZiI6MTcxMDA3OTgyOSwicGF0aCI6Ii80MzQ3ODYwMi8zMTEzODMyNDEtZDgzNzBhZjQtYWViNS00MmJjLTgxN2YtZWVjZWNmZWFiZDY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE0MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzZhNjU4Zjc4MDRmZDFkYjI1NmE4Y2ZiNzY3ODFjYzczMDI0ZWI1OTAzMjQ3NDQ1ZDY2MWJmNjEzY2UyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iu3tZoi7uCHY5V_VlV337mvN6OipQq0Xtk7ExCxn8RA)

Here are the mapped contact:

| Pin U3 | Pin U4 |
| ---------- | ---------- |
| 1 | 1 |
| 2 | N.C. |
| 3 | N.C. |
| 4 | 3 |
| 5 | 4 |
| 6 | N. C. |
| 7 | 5 |
| 8 | 6 |
| 9 | 2 |
| 10 | N. C. |
| 11 | N. C. |
| 12 | N. C. |
| 13 | N. C. |
| 14 | N. C. |
| 15 | N. C. |
| 16 | N. C. |

![K9_Pins_U3_to_U4](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/38381946/25f5f4ca-eb90-47f5-8895-e9f38a7cc16c)

**Comment by Ajimaru** [comment]
> Hmm, the buttons are mapped the same way. I don't know what the cause of the issue is and I'm out of ideas, sorry

I may have to copy the **lite_cfg.txt** also on the SD-Card?

**Comment by JohnTheCoolingFan** [comment]
I don't know, my firmware worked without issues. Sorry, but I can't help much without actual hardware that has the issue to experiment with.

**Comment by schmttc** [comment]
@Ajimaru I've compiled the code from the K9 branch here and the file size is different to the file John uploaded (134KB vs 118KB)
Can you try this one? (remove the .txt when you put it on the SD card)
[mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/14570021/mksLite.bin.txt)

lite_cfg.txt doesn't do anything in this version of the firmware.

**Comment by Ajimaru** [comment]
> @Ajimaru I've compiled the code from the K9 branch here and the file size is different to the file John uploaded (134KB vs 118KB) Can you try this one? (remove the .txt when you put it on the SD card) [mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/14570021/mksLite.bin.txt)
> 
> lite_cfg.txt doesn't do anything in this version of the firmware.

@schmttc with your compiled bin file the leveling buttons on the K9 are working.
To make some things clear, I use Octoprint to control the printer.
With the factory firmware Octoprint can control all functions of the K9.
But with your compiled Marlin Firmware only heating the Nozzle and the Bed is working.
Moving the X, Y & Z axis does not work.

I would love to the the K9 fully functional with Marlin to make use of the heat bed.

**Comment by schmttc** [comment]
> @schmttc with your compiled bin file the leveling buttons on the K9 are working. To make some things clear, I use Octoprint to control the printer. With the factory firmware Octoprint can control all functions of the K9. But with your compiled Marlin Firmware only heating the Nozzle and the Bed is working. Moving the X, Y & Z axis does not work.
> 
> I would love to the the K9 fully functional with Marlin to make use of the heat bed.

If the levelling buttons are working, then the motion steppers are configured OK. I wonder if there is an issue between Octoprint and some setting in the firmware.

@Ajimaru 
1. "Moving the X, Y & Z axis does not work." is this when manually controlling motion with the Octoprint GUI?
2. Does motion work when running a print job from gcode?

**Comment by Ajimaru** [comment]
> > @schmttc with your compiled bin file the leveling buttons on the K9 are working. To make some things clear, I use Octoprint to control the printer. With the factory firmware Octoprint can control all functions of the K9. But with your compiled Marlin Firmware only heating the Nozzle and the Bed is working. Moving the X, Y & Z axis does not work.
> > I would love to the the K9 fully functional with Marlin to make use of the heat bed.
> 
> If the levelling buttons are working, then the motion steppers are configured OK. I wonder if there is an issue between Octoprint and some setting in the firmware.
> 
> @Ajimaru
> 
>     1. "Moving the X, Y & Z axis does not work." is this when manually controlling motion with the Octoprint GUI?
> 
>     2. Does motion work when running a print job from gcode?

@schmttc I have found the rootcause, after update the firmware a file named **EEPROM.DAT** was created on the SD Card.
To use the Marlin firmware an SD Card with this file on it need to inserted.

**Comment by schmttc** [comment]
> @schmttc I have found the rootcause, after update the firmware a file named **EEPROM.DAT** was created on the SD Card. To use the Marlin firmware an SD Card with this file on it need to inserted.

Thanks for your persistence. I have an outstanding action to implement EEPROM correctly #5

**Comment by Ajimaru** [comment]
Well I should have a closer look to the closed issues next time.
Besides the EEPROM everything is working as expected, thanks for the work.

**Comment by novadaemon1** [comment]
> @Ajimaru I have enabled the onboard EEPROM and uploaded the new binary to the K9 branch [9338b48](https://github.com/schmttc/EasyThreeD-K7-STM32/commit/9338b4863de90db6eae2fcedd507d36d76772c6b), if you try it please let me know the results

Just wanted to let you know that the firmware works with the buttons just fine, but it has some quirks. For example, Z axis homing takes way too long and grinds the motor significantly more than stock firmware. Once I figure out all the issues I will let you know.

**Comment by Ajimaru** [comment]
> @Ajimaru I have enabled the onboard EEPROM and uploaded the new binary to the K9 branch [9338b48](https://github.com/schmttc/EasyThreeD-K7-STM32/commit/9338b4863de90db6eae2fcedd507d36d76772c6b), if you try it please let me know the results

I can confirm that this firmware is working now with out the EEPROM.DAT file spresent on the SD-Card.
I also noticed the grinding noise when the Z-Motor has reached the physical endstop.
This behaviour is not present in the stock firmware.

As a request can you please add [Host Action Commands](https://marlinfw.org/docs/configuration/configuration.html#host-action-commands) ?

**Comment by JohnTheCoolingFan** [comment]
> I also noticed the grinding noise when the Z-Motor has reached the physical endstop.

I have noticed something similar, which is that it twitches when reaches the physical end stop, trying to step further and I think skipping steps/sequences of steps because of that. The original firmware might have had some mechanism to detect when a motor is not moving the axis any further, or they just drive it differently so that it reaches the end smoothly.

Speaking of motors: I have noticed that my motors are heating up a lot even at idle! I didn't test with the stock firmware, though. The screw that holds the cam in place is very hot, as is the bracket that holds down the motor. Is it a common thing in 3d printing? Should I be worried about damage to motors or parts of the printer?

**Comment by JohnTheCoolingFan** [comment]
Ah, and another note, regarding the main button behavior. Holding it down when printing is in progress doesn't stop the print immediately, but probably stops the queue from filling up, a number of operations sill still execute. The sock firmware stops the print immediately.

Also, after the print is finished, the button is still flashing like it's in printing mode, but it had already finished the routine (homed x and y axes). Holding down the button would stop the print and then revert to the default behavior of moving the print head 1cm up when held down for 3 seconds.

**Comment by schmttc** [comment]
1. @Ajimaru I'll get host action commands added to the binary soon.

2. Can one of you please upload a copy of the original lite_cfg.txt, I have a theory about the homing and heat issues, maybe the vendor has reduced the current, these steppers are only rated for around 250ma and this firmware provides 1A. I didn't notice an issue on the K7 but the steppers are enclosed.
Less current means less heat (steppers are always 'on' even when not moving); and less torque so the motor will stall more easily as the end of homing and not crunch as the belt slips.

Regarding button behaviour
3. The Marlin devs didn't like the hard stop when I merged into mainline, but happy to change it back because it makes more sense and replicates out of box behaviour.
4. Button still flashing after print sounds like a bug, can fix the state

**Comment by schmttc** [comment]
@Ajimaru @JohnTheCoolingFan 
Here's a binary to test with items 1,2 and 3 addressed plus 5.  speed increase on Z homing , can you let me know if it works or what doesn't?
4. needs more time than I have at the moment
 
[mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/15258067/mksLite.bin.txt)

**Comment by Ajimaru** [comment]
> 1. @Ajimaru I'll get host action commands added to the binary soon.
> 
>     2. Can one of you please upload a copy of the original lite_cfg.txt, I have a theory about the homing and heat issues, maybe the vendor has reduced the current, these steppers are only rated for around 250ma and this firmware provides 1A. I didn't notice an issue on the K7 but the steppers are enclosed.
>        Less current means less heat (steppers are always 'on' even when not moving); and less torque so the motor will stall more easily as the end of homing and not crunch as the belt slips.
> 
> 
> Regarding button behaviour 3. The Marlin devs didn't like the hard stop when I merged into mainline, but happy to change it back because it makes more sense and replicates out of box behaviour. 4. Button still flashing after print sounds like a bug, can fix the state

@schmttc here is the factory [lite_cfg.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/15258391/lite_cfg.txt)

**Comment by Ajimaru** [comment]
> 1. @Ajimaru I'll get host action commands added to the binary soon.
> 
>     2. Can one of you please upload a copy of the original lite_cfg.txt, I have a theory about the homing and heat issues, maybe the vendor has reduced the current, these steppers are only rated for around 250ma and this firmware provides 1A. I didn't notice an issue on the K7 but the steppers are enclosed.
>        Less current means less heat (steppers are always 'on' even when not moving); and less torque so the motor will stall more easily as the end of homing and not crunch as the belt slips.
> 
> 
> Regarding button behaviour 3. The Marlin devs didn't like the hard stop when I merged into mainline, but happy to change it back because it makes more sense and replicates out of box behaviour. 4. Button still flashing after print sounds like a bug, can fix the state

I can confirm that 1. & 2. are fixed, good job tahnk you!
3. & 4. I can not test because I use Octoprint to control the printer.

**Comment by schmttc** [comment]
Thanks for the file and confirming the results @Ajimaru 

The stepper current is 750/800ma in your config file, and I've reduced it to 500 from 1000, which is still double the rated 200ma so it should be fine. But if you get layer shifting problems or it feels like the printer is skipping steps, we can return it to the default setting.

These changes are in the 'k9-fixes' branch, I'll merge it with ET4000PLUS-K9 once the other changes are confirmed.

**Comment by JohnTheCoolingFan** [comment]
> @Ajimaru @JohnTheCoolingFan Here's a binary to test with items 1,2 and 3 addressed plus 5. speed increase on Z homing , can you let me know if it works or what doesn't? 4. needs more time than I have at the moment
> 
> [mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/15258067/mksLite.bin.txt)

Trying out this firmware right now, immediately can say that it is much more quiet, no noise when reaching ends. The motors are not heating up, but I'm wondering how that would affect performance (skipped steps, layer shifts, lesser acceleration, printing speed). I like how fast the printer is with the custom firmware compared to stock. Doing a test print  now, will post an update later

**Comment by schmttc** [comment]
> Trying out this firmware right now, immediately can say that it is much more quiet, no noise when reaching ends. The motors are not heating up, but I'm wondering how that would affect performance (skipped steps, layer shifts, lesser acceleration, printing speed). I like how fast the printer is with the custom firmware compared to stock. Doing a test print now, will post an update later
[mksLite.bin.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/15268414/mksLite.bin.txt)

Here's one with the out of box current settings you can try as well. Let me know if the homing is still smooth and the heat OK, hopefully this is the right balance.

**Comment by JohnTheCoolingFan** [comment]
The motors heat is OK, getting a bit warm to the touch and just that. I haven't noticed layer shifts or skipped steps, only some backlash in the axes, which can be seen on a benchy, for example. In the compartment behind the cabin the wall might have a consistent gap between it and the edge of the top surface ![photo](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/43478602/8f91fb6d-2b3a-4133-bf13-20eb6d282852)
Accounting for that would probably require klipper, but  it's not a big issue for my prints.

**Comment by JohnTheCoolingFan** [comment]
There  is an issue with the interface though: holding down the button for 3 seconds while printing stops the print, but after that the printer does not react to the action (trying to move the print head up)

**Comment by schmttc** [comment]
Thanks @JohnTheCoolingFan 

Regarding backlash, you can set backlash compensation in Marlin with [M425](https://marlinfw.org/docs/gcode/M425.html). The Klipper folk don't do backlash compensation, their stance is that it should be resolved in the hardware, which is not possible with these printers.
I use this tower to tune backlash settings https://www.thingiverse.com/thing:2371069

I'll look into the interface issue over the next week or two as I find time, will compile for my K7 so I can test before sending it over.
If you want to use this firmware until then I suggest a quick power on/off between prints.

**Comment by JohnTheCoolingFan** [comment]
@schmttc thanks for the tools for backlash compensationm, but I've re-encountered  https://github.com/MarlinFirmware/Marlin/issues/23741 when  I  added the gcode, looks like you had or still have this problem too.
![2024-05-26 12-06-47](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/43478602/348f2222-49c9-444a-bbea-173a4e977fd9)
![2024-05-26 12-06-53](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/43478602/4963a1e7-ca29-4b98-9407-88599e72deac)

**Comment by JohnTheCoolingFan** [comment]
Ah, this is tracked in #2

**Comment by JohnTheCoolingFan** [comment]
Update on backlash compensation: I've managed to merge `backlashfix` into `k9-fixes` and compile that, which resolved the issue. I have calibrated my printer and now I use a 0.32mm backlash compensation value for all axes, as they are completely identical. I can probably put that into the firmware, but I don't want to do that right now. I still  have a problem of seemingly squished first few layers.
The circles have become noticeably more round and less square, which is very nice to see. Still, a 3mm hole turned out to be 2.75mm on average.

**Comment by schmttc** [comment]
Great! 
Regarding squashed first layers, try adding some start gcode to your slicer that raises the head say 0.2mm (or whatever you determine)
And for slightly small/large holes, try tweaking Horizontal Expansion (at least that's what it's called in Cura)

**Comment by JohnTheCoolingFan** [comment]
And regarding squashed first layers, I think I am noticing some **scratching** on my bed surface, even though I leveled it.

**Comment by JohnTheCoolingFan** [comment]
And here's the gcode file I've been using: 
[CFFFP_3DBenchy.gcode.txt](https://github.com/schmttc/EasyThreeD-K7-STM32/files/15502920/CFFFP_3DBenchy.gcode.txt)

**Comment by schmttc** [comment]
**Layer Shift**
Looking back at #2 , this could be a more complex issue that's not fully resolved.
1. It's hard to tell where the shifting occurs from that photo, can you change the angle to more side on?
2. Originally the layer shift was only occurring sometimes, but was linked to acceleration. 100mm/s/s always caused shift, 20mm/s/s always didn't. But for my smaller tests the current code fixed the issue. What acceleration and speed are you using? Have you overridden the max speeds and acceleration in your firmware? Can you provide a link to the current code you're using?
3. The shift would show up soon for smaller layer - I see you're using 0.1 from your gcode. Can you try 0.2 layers and see if the shift shows up later? 
4. Comparing the code I worked on with Tom and what was merged back into Marlin, he made some changes on his end afterwards https://github.com/MarlinFirmware/Marlin/pull/26392
So it might be worth trying that.

**Squashed Layers**
I think the backlash comp should be pushing the head up not further down; but try adding some start gcode to lift the head by say 0.4mm

**Comment by JohnTheCoolingFan** [comment]
I've re-leveled the bed at 60C and now trying to print benchy with 0.2mm layer height. The heat from the hotbed causes the bottom plastic bracket to warp! That may be the cause of squashed layers, I'll have to see.

Regarding layer shifts, here is a better picture: 
![image](https://github.com/schmttc/EasyThreeD-K7-STM32/assets/43478602/bab35442-ce8c-4b46-97d9-4db215da12aa)
I've already broken the piece up into small pieces for 3d printed waste storage, can't take more pictures.
I can probably try with different speed, but only on 0.2mm layers, because even with the current speeds it takes much more time than cura predicts.

**Comment by JohnTheCoolingFan** [comment]
The code I use to compile the firmware is located here: https://github.com/JohnTheCoolingFan/EasyThreeD-K7-STM32/tree/k9-fixes-backlashfix

**Comment by JohnTheCoolingFan** [comment]
The 0.2mm layer benchy printed without any issues.

**Comment by JohnTheCoolingFan** [comment]
I've printed a few tests  for bed leveling and discovered that yes, my bed is too close to the nozzle. A layer 1 line had a width of 0.82mm and height of 0.16mm. I'll use a Z offset through gcode first, then will think on more permanent ways of avoiding that problem.
Oh, and the 10mm squares in the bed leveling calibration shape turned out as 10.49-10.72 squares.

**Comment by JohnTheCoolingFan** [comment]
I've completed leveling for my 3d printer, still needs adjustments from time to time. But now I'm having an issue where the motors stall at some moves, `G0` or `G1`, just a segment. Causing the whole print to shift. I've moved the backlash to firmware and rebased everything to exclude `backlashfix`. Now I'm upping the current from 0.5A to 0.8A in hopes that it will help with motors stalling. I'm planning to do an upgrade from the channel Made With Layers and currently trying to print reverse-engineered modified split shell inserts.

**Comment by Rixxxi** [comment]
Hi guys,
I'm tinkering on my son's EasyThreeD X1 with ET-4000 V2 mainboard and 264-motors on X and Y axis (set to 607 and 605 steps/mm). Mid last year I compiles a firmware with backlash compensation, was suffering from layer shifts and gave up on it since then. 

Last week, after reading through [Layer Shifts issue #2](https://github.com/schmttc/EasyThreeD-K7-STM32/issues/2) I compiled [Marlin 2.1.2.4](https://github.com/MarlinFirmware/Marlin/releases/tag/2.1.2.4) with my own created Configuration.h and Configuration_adv.h (attached). To wrap it up: My configs have backlash compensation, linear advance as well as a LCD-display + encoder enabled (#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER -> https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller ). 
My understandig is that 2.1.2.4 should have a the fix for the Layer Shifts issue #2 included. Is that correct?

I calibrated the backlash using the [backlash tower from Thingiverse](https://www.thingiverse.com/thing:2371069) and this values gave me nice results: #define BACKLASH_DISTANCE_MM { 0.435, 0.63, 0.255 }
I have not enabled BACKLASH_SMOOTHING_MM so far. Is it recommended to do so?

Already last year in my tests more than 30mm/s speed was causing issues and since then I'm running the printer on DEFAULT_MAX_FEEDRATE { 30, 30, 15, 50 }. Is anyone runnig the 264-motors on 40mm/s without issues ?

For acceleration I didn't make too detailed tests on our printer, but since I read somewhere that 300mm/s² should not be exceeded I compiled with #define DEFAULT_MAX_ACCELERATION { 150, 150, 100, 150 } to be on the safe side.
Lately we finally started a [bigger print](https://www.thingiverse.com/thing:5165613) (downscaled to about 48%) for my son with a lot of details in it. And we were suffering layershifts again :-( 
I adjusted the acceleration down to 100mm/s² for X and Y but still got layer shifts. I gave up on it again.
Now I read this:
>     2. Originally the layer shift was only occurring sometimes, but was linked to acceleration. 100mm/s/s always caused shift, 20mm/s/s always didn't. But for my smaller tests the current code fixed the issue. 
Can you explain a little more about what you found out on the acceleration? Which acceleration settings work, which don't? Is it simple as "lower acceleration is always more safe then higher" or are there particular acceleration settings that will/won't work?

**Comment by JohnTheCoolingFan** [comment]
Now I'm getting really weird layer shifts, in this print they are on the X axis. Previously they were on the Y axis, and this is unrelated to backlash compensation, as it was put into firmware. I have basically all components and models to start an upgrade of the printer, but it suddenly decided to not produce usable prints anymore. Very weird...

![2024-07-13 13-53-37](https://github.com/user-attachments/assets/8ef8bc34-5795-4d4f-8d7e-814d090cb844)
![2024-07-13 13-53-39](https://github.com/user-attachments/assets/9605198e-7c7a-42d8-b4d4-9565fe7f4b2c)
![2024-07-13 13-53-41](https://github.com/user-attachments/assets/b822d485-9caf-4fa8-a5ee-e3f8c067693f)

**Comment by Rixxxi** [comment]
Those layer shifts are really anoying. I hope we can get them sorted out finally one day.

> this is unrelated to backlash compensation, as it was put into firmware.
What do you mean?

**Comment by JohnTheCoolingFan** [comment]
My issues started appearing after I've disassembled the Y axis, there were no layer shifting issues with the firmware I used before the disassembly and reassembly.
I've put the backlash compensation config values into the firmware (so instead of gcode I put it in the Marlin Configuration file)

**Comment by Rixxxi** [comment]
> I've put the backlash compensation config values into the firmware (so instead of gcode I put it in the Marlin Configuration file), which avoids the issue.

Thanks. I wasn't aware that Configuration file vs. GCODE makes any difference. Is this a known problem?
However, I had my backlash compensation in the Configuration file all the time. So it won't make a difference for my layer shift problems.

**Comment by schmttc** [comment]
@Rixxxi I'm not actively using this printer any more, but:

>My understandig is that 2.1.2.4 should have a the fix for the Layer Shifts issue https://github.com/schmttc/EasyThreeD-K7-STM32/issues/2 included. Is that correct?

From what I can see yes this fix should be in main Marlin now, it was merged to bugfix in Nov 23 and there's been a few releases since then. You can compare the code to confirm.

>I have not enabled BACKLASH_SMOOTHING_MM so far. Is it recommended to do so?

Smoothing averages out the backlash over a longer distance, which gives smoother but less precise results. I haven't done any testing with this feature.

> Can you explain a little more about what you found out on the acceleration? Which acceleration settings work, which don't? Is it simple as "lower acceleration is always more safe then higher" or are there particular acceleration settings that will/won't work?

I used two test scenarios, 20mm/s/s and 100mm/s/s, but didn't do any tuning to figure out where the upper limit of 'safe' is.
But then when the backlash correction fix was implemented, I could use 100mmss accelerations again, but didn't do any extensive testing.
But based on John's and your results, it looks like there is still an acceleration limit with recent firmware and these printers. If in your testing 30mmss is safe, but 40mmss isn't, that aligns with my results and gives us a better data point that 30mms is the safe limit.

Why the newer firmware only works with low acceleration but the older firmware seems to work with higher acceleration is a question I don't know the answer to. It would probably need lots of testing between new and old and probably isn't worth the time given I found the linear print speed is limited to 40mm/s to get quality prints.

**Comment by Rixxxi** [comment]
@schmttc thanks for getting back on my questions.

> You can compare the code to confirm.

I will do so.

> But based on John's and your results, it looks like there is still an acceleration limit with recent firmware and these printers. If in your testing 30mmss is safe, but 40mmss isn't, that aligns with my results and gives us a better data point that 30mms is the safe limit.

The value of 30 was in my case the print speed ("feed rate") in mm/s and not the acceleration (mm/s²). I was wondering if this could be a limitation of the 264-motors. As their gearbox has a higher reduction compared to the 586-motors, I could imagine that only 586 motors are able to print with 40mm/s and the 264-motors probably don't. But I couldn't find any information about this so far.

> Why the newer firmware only works with low acceleration but the older firmware seems to work with higher acceleration is a question I don't know the answer to. 

Can you tell a firmware version that shall be safe to print with "high" acceleration? What acceleration value did you use with it? Can you tell the type of motors (type 264 = ca. 467 steps // type 586 = ca. 606 steps) your printer is based on?

**Comment by schmttc** [comment]
- Apologies for the mix up. I print at 40mm/s speed, which ensures a good quality print. I tried 60mm/s but the print quality suffered in general. And I tried printing at 120mm/s in vase mode when testing the Input Shaping feature, it worked ok but sometimes had layer shifts
- Checking Aliexpress, is seems the 264 motor has a 32x reduction, and the 586 motor has a 64x reduction. My intuition is that a bigger reduction has more inertia in the geartrain and so would cause more problems at higher speed or acceleration
- From testing I think the layer shifts are more related to acceleration than speed
- The firmware that worked with 'high' acceleration is the original v1.1 firmware :) I can't recall what settings I used but probably the firmware default 300mms2

**Comment by Rixxxi** [comment]
> Checking Aliexpress, it seems the 264 motor has a 32x reduction, and the 586 motor has a 64x reduction.

It's correct, they have a different reduction. I'm unsure about the actual reduction factors. According to [this post](https://www.reddit.com/r/EasyThreeD/comments/oe0qyf/comment/h4k33wb/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) there are motors with 1:32 and 1:25 reduction. The same redit guy (Melodic_Winner9531) has published parts of this Marlin/Slicer configuration [here](https://daduke.org/hardware/X1/) which includes the following step settings:
`M92 X597.76 Y597.76 Z1160.00 E1040.00 ; Unit A, 1:32 gears`
`M92 X467.00 Y467.00 Z1160.00 E1040.00 ; Unit B, 1:25 gears`

I measured&calibrated EasyThreeD X1 printer's steps for X and Y axis and they are 607 and 605 steps/mm, which correlates with the 1:32 gears. Assuming the 1:32 and 1:25 recution are correct and the only motor/gearbox configurations EasyThreeD is using, I have the motors with the bigger reduction.
Side note: I read somewhere, that the 1:32 motors have metal gears and the 1:25 motors have plastic gears. I assume this could also affect the maximum acceleration/speed possible to achieve. 

> I print at 40mm/s speed, which ensures a good quality print. I tried 60mm/s but the print quality suffered in general. And I tried printing at 120mm/s in vase mode when testing the Input Shaping feature, it worked ok but sometimes had layer shifts

I'm very surprised about this. I tested the maximum speeds of my printer performing simple linear movements using Pronterface with Marlin commands. My motors completely stalled and made loud rattle noise when pushing them faster than 33mm/s ! That's why I'm currently running them @ 30mm/s. However I have to admit that I'm not sure about the acceleration settings during that tests. I think I altered them down to 150mm/s² or even lower while testing, but I'm not sure. I might test that again when I find time.


> My intuition is that a bigger reduction has more inertia in the geartrain and so would cause more problems at higher speed or acceleration

My intuition is the same :-)
As you were able to achieve much higher speeds than me: What motors/reduction is your printer based on? Can you please check the steps your Marlin is configured to (M92 / #define DEFAULT_AXIS_STEPS_PER_UNIT ) ?

**Comment by schmttc** [comment]
My K7's X/Y/Z/E steps are { 606, 606, 1167, 1140 }

The loud rattle noise is probably the belts slipping, try and tighten X and Y and see if that helps.
When the steppers don't have enough current and stall the noise is a softer clicking.

**Comment by Rixxxi** [comment]
I re-tested my X and Y axis speeds of my X1 performing simple linear movements using Pronterface and G0 GCODE commands. Indeed I was able to push it up to 55mm/s at 400mm/s² on 2.1.2.4 firmware. That is much faster then I thought it would go. I'm not planning to run the printer that fast in real life, but it's good to know that my 30mm/s are not close to the machine the limits. When I tried to go faster than 55m/s then the axis are not really moving accordingly and it's making a noise. But other than I remembered before, it's not a rattle noise that could be related to the belt slipping. Also, it's not a clicking sound. The noise not really loud and hard for me to describe. It's a continuous noise for 1-2 seconds and the motors stop moving while it appears. 

This asside, I still need to sort out my layer shift issues. I realized that in backlash.cpp there are quite some differences between my version 2.1.2.4 (latest official release) and the newest code in GitHub (CONFIGURATION_H_VERSION 02010300). I can't tell what the actual difference is. So I downloaded the 2.1.3.0 (unreleased) and just compiled it a few minutes ago. Will give it a try tonight.

**Comment by Rixxxi** [comment]
Good news!
I'm printing with the 2.1.3.0 firmware at 40mm/s and 150mm/s² acceleration a [complex model](https://www.thingiverse.com/thing:5165613) (downscaled to about 48%) which always caused layer shifts when printing it with 2.1.2.4 firmware. I'm printing the exact same GCODE and so far (20% print done) no layer shifts visible!

**Comment by schmttc** [comment]
> Good news! I'm right now printing with the 2.1.3.0 firmware at 40mm/s and 150mm/s² acceleration a [complex model](https://www.thingiverse.com/thing:5165613) (downscaled to about 48%) which always caused layer shifts when printing it with 2.1.2.4 firmware. I'm printing the exact same GCODE and so far (20% print done) no layer shifts visible!
> 
> EDIT: The GCODE is sliced with maximum of 30mm/s and 150mm/s². So it's not really printing with 40mm/s even if the firmware limit is set to 40mm/s. This does not make the success any smaller. The important fact is that there are no layer shifts any more!

This is good news!
Did you use the ET4000PLUS-K9 branch as a base? Could you create a PR or provide a repo so we can integrate the changes here?

**Comment by JohnTheCoolingFan** [comment]
Ok, I've flashed [this firmware file](https://github.com/schmttc/EasyThreeD-K7-STM32/blob/20807069b8738112c93aa66a9a9440846fe3d334/mksLite.bin) from the branch `ET4000PLUS-K9`, and it doesn't result in layer shifts so far. What was causing them for me is putting the backlash compensation values into the firmware (Configuration headers). The backlash compensation bug exists on this branch it seems. I haven't tried backlash compensation set via gcode though.

**Comment by novadaemon1** [comment]
I don't know what the issue is, but every custom firmware that I've tried seems to break something. In the latest mkslite.bin, USB control is broken. I cannot control the printer via USB in Cura. If anyone could verify this, that would be appreciated. Flashing back to factory firmware resolves the issue but then I am stuck on stock firmware.

**Comment by schmttc** [comment]
> I don't know what the issue is, but every custom firmware that I've tried seems to break something. In the latest mkslite.bin, USB control is broken. I cannot control the printer via USB in Cura. If anyone could verify this, that would be appreciated. Flashing back to factory firmware resolves the issue but then I am stuck on stock firmware.

Can you please raise a new issue to track this item?

I've done some background reading and compared the configuration; can you please try the firmware on this branch and let us know if it works or breaks anything else? https://github.com/schmttc/EasyThreeD-K7-STM32/tree/cura-usb-fix

**Comment by schmttc** [comment]
> Ok, I've flashed [this firmware file](https://github.com/schmttc/EasyThreeD-K7-STM32/blob/20807069b8738112c93aa66a9a9440846fe3d334/mksLite.bin) from the branch `ET4000PLUS-K9`, ~and it doesn't result in layer shifts so far. What was causing them for me is putting the backlash compensation values into the firmware (Configuration headers). The backlash compensation bug exists on this branch it seems. I haven't tried backlash compensation set via gcode though.~
> 
> No, layer shifts simply appear later during print, with [this firmware with backlash compensation](https://github.com/JohnTheCoolingFan/EasyThreeD-K7-STM32/blob/02a40ca3f497e4713428f9af3b21e854576a7100/mksLite.bin) layer shifts appear on relatively low layers. With current firmware, even without backlash compensation enabled, layer shift happened while printing a benchy at layer 40, a shift of about 20.8mm in negative X direction, using this gcode file: [CFFFP_3DBenchy.gcode.txt](https://github.com/user-attachments/files/16623876/CFFFP_3DBenchy.gcode.txt)

Based on the feedback above I think the next step is to uplift to 2.1.3.0; @Rixxxi can you provide a copy of your source code to save us the rework?

**Comment by Rixxxi** [comment]
> Good news! I'm right now printing with the 2.1.3.0 firmware at 40mm/s and 150mm/s² acceleration a [complex model](https://www.thingiverse.com/thing:5165613) (downscaled to about 48%) which always caused layer shifts when printing it with 2.1.2.4 firmware. I'm printing the exact same GCODE and so far (20% print done) no layer shifts visible!
> 
> EDIT: The GCODE is sliced with maximum of 30mm/s and 150mm/s². So it's not really printing with 40mm/s even if the firmware limit is set to 40mm/s. This does not make the success any smaller. The important fact is that there are no layer shifts any more!

This print came out fine without any layer shifts, indeed.


> This is good news! Did you use the ET4000PLUS-K9 branch as a base? Could you create a PR or provide a repo so we can integrate the changes here?

Sorry I haven't replied yet. I'm not very familiar with GitHub and would have needed to learn how to correcply create a PR with my code version and changes. 
But...

> Based on the feedback above I think the next step is to uplift to 2.1.3.0; @Rixxxi can you provide a copy of your source code to save us the rework?

After the successful print mentioned above with 2.1.3.0 firmware I didn't touch the printer for a while.
Now, three days ago my son wanted to print this rather simple [penguin](https://www.thingiverse.com/thing:22981). Scaled to 99mm height and sliced with 40mm/s print speed in OrcaSlicer. We started the print and **got layer shifts again :-(**
I was really frustrated about it, but tried another attempt. This time I limited the acceleration to 100mm/s² in the printer firmware (I have a LCD-screen attached to do the printer. So the firmware wasn't re-compiled, just configured at runtime via the LCD). With 100mm/s² the layer shifts occured at _other_ positions/layers than before. Then I kept the printer on (not power-cycling it), kept all settings the same (still 100mm/s²) and re-printed the model again. This time layer shifts occured and _other_ positions than in both prints before.

There is one thing that seams to be different now with the 2.1.3.0 firmware. But I can't 100% verify it:
When printing [this model](https://www.thingiverse.com/thing:5165613) with 2.1.2.4 firmware, the layershifts were quite small. Maybe 1mm or even less. The result was more like the model wasn't printed exactly straight, but with a slight angles in it. The same for the [backlash tower](https://www.thingiverse.com/thing:2371069).
Now with 2.1.3.0 printing the penguin caused layershifts of ~5mm. Maybe this is somehow a hint for something.

If I find the time I'll try around some more with 2.1.3.0 and different print speeds etc.

**Comment by schmttc** [comment]
I'm wondering if we haven't ruled out a mechanical source of the shifts - the little stepper motors have a high reduction in them.
When I was doing testing I never encountered backlash when I set acceleration to 20mm/s/s
Can you try a similar value and let us know if the backlash still occurs?

**Comment by Rixxxi** [comment]
> Can you try a similar value and let us know if the backlash still occurs?

What shall we test? Run backlash test prints (e.g. the [backlash tower](https://www.thingiverse.com/thing:2371069) ) at 20mm/s/s with _**disabled**_ backlash compensation?
> 
> Edit: But it doesn't happen on original firmware. So maybe we need to look into all of the acceleration and jerk and smoothing and smart motion settings, try disabling them all

That's also what I wonder: What's the actual difference between original and custom firmware to cause the layer shifts? We have to consider, that the original firmware is v1.x and our custom firmware with backlash compensation is v2.1.x

I'm also wondering if the small MCU on the mainboard might be unable to cope with the complexity of a 2.1.x firmware and by this somehow cause processing delays and/or loose stepping commands etc. In my case it additionally has to handle the LCD-display + encoder I'm using (#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER -> https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller ). But I'm far too inexperienced with MCU programming to be able to estimate whether such effects could occur.

**Comment by schmttc** [comment]
> > Can you try a similar value and let us know if the backlash still occurs?
> 
> What shall we test? Run backlash test prints (e.g. the [backlash tower](https://www.thingiverse.com/thing:2371069) ) at 20mm/s/s with _**disabled**_ backlash compensation?
> 
> > Edit: But it doesn't happen on original firmware. So maybe we need to look into all of the acceleration and jerk and smoothing and smart motion settings, try disabling them all
> 
> That's also what I wonder: What's the actual difference between original and custom firmware to cause the layer shifts? We have to consider, that the original firmware is v1.x and our custom firmware with backlash compensation is v2.1.x
> 
> I'm also wondering if the small MCU on the mainboard might be unable to cope with the complexity of a 2.1.x firmware and by this somehow cause processing delays and/or loose stepping commands etc. In my case it additionally has to handle the LCD-display + encoder I'm using (#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER -> https://reprap.org/wiki/RepRapDiscount_Full_Graphic_Smart_Controller ). But I'm far too inexperienced with MCU programming to be able to estimate whether such effects could occur.

Use a print that you know fails with backlash correction on at > 100mms2 acceleration; and test the same model at 20mms2 acceleration.  This will tell us if the issue is cause by backlash correction or something else.

There have been a lot of improvements to motion over the years between Marlin 1 and today (Our firmware is only custom in the button interface). I suspect that there are new features (eg. jerk vs classic acceleration) that may have an impact; but there may also be changes to the underlying 'base' features that are causing problems as well. I hope the problem is the former. 

The MCU is 32 bits and pretty capable, I don't think you're asking too much of it. And other people have the same layer shift issues and no additional features.

**Comment by Rixxxi** [comment]
> Use a print that you know fails with backlash correction on at > 100mms2 acceleration; and test the same model at 20mms2 acceleration. This will tell us if the issue is cause by backlash correction or something else.

Understood. I will do so!

> The MCU is 32 bits and pretty capable, I don't think you're asking too much of it. And other people have the same layer shift issues and no additional features.

My EasyThreeD X1 is running a ET-4000 V2 mainboard (this was stock in my printer) with Atmega1284P MCU, which is 8-bit AFAIK.

**Comment by schmttc** [comment]
> [novadaemon1](/novadaemon1)

@novadaemon1 I just tested my K7 with the firmware binary in the main branch, and Cura 5.4 connected after about 30s and I was able to control it.
This is without the code modifications I made to the branch I mentioned earlier. 
Given it's the same mainboard, I suspect you may have a different issue. What version of Cura are you running? some older versions had a problem with USB control
And have you tried another cable?

**Comment by novadaemon1** [comment]
> > [novadaemon1](/novadaemon1)
> 
> @novadaemon1 I just tested my K7 with the firmware binary in the main branch, and Cura 5.4 connected after about 30s and I was able to control it. This is without the code modifications I made to the branch I mentioned earlier. Given it's the same mainboard, I suspect you may have a different issue. What version of Cura are you running? some older versions had a problem with USB control And have you tried another cable?

So I figured out what was wrong. I basically needed to reset everything with an M503 command on stock firmware then I was able to flash the current firmware and everything is fine, so the USB fix isn't needed.

More importantly, I found something interesting the other day.

https://www.printables.com/model/981788-marlin-2-easythreed-k9-with-et4000/files

This guy made his own custom firmware based on yours and his settings actually worked pretty well. He uploaded his configuration after I asked him to. Please check it out.

**Comment by schmttc** [comment]
> > > [novadaemon1](/novadaemon1)
> > 
> > 
> > @novadaemon1 I just tested my K7 with the firmware binary in the main branch, and Cura 5.4 connected after about 30s and I was able to control it. This is without the code modifications I made to the branch I mentioned earlier. Given it's the same mainboard, I suspect you may have a different issue. What version of Cura are you running? some older versions had a problem with USB control And have you tried another cable?
> 
> So I figured out what was wrong. I basically needed to reset everything with an M503 command on stock firmware then I was able to flash the current firmware and everything is fine, so the USB fix isn't needed.
> 
> More importantly, I found something interesting the other day.
> 
> https://www.printables.com/model/981788-marlin-2-easythreed-k9-with-et4000/files
> 
> This guy made his own custom firmware based on yours and his settings actually worked pretty well. He uploaded his configuration after I asked him to. Please check it out and check out some settings he posted in the comments.

I've compared the changes here, analysis below: https://github.com/schmttc/EasyThreeD-K7-STM32/compare/ET4000PLUS-K9...ET4000PLUS-K9-Denis_2329928

@novadaemon1 what model of printer do you have, I can whip up a quick binary with the new settings to test if you like?

Increase max Z feedrate from 10 to 60mm/s; 
Reduced Max and Default Acceleration from 1000 to 500;  This would help if you're not setting acceleration in your slicer
Increase ejerk from 2 to 8; If anything I would expect this to make problems worse rather than make it less
Increased homing feedrate from 40mm/s to 90mm/s; as above

**Comment by schmttc** [comment]
Dumping this here for future reference; vendor recommended motor currents for the K7, should be similar for K9

https://www.reddit.com/r/EasyThreeD/comments/1477nz4/messed_up_my_motor_drivers_vref_settings/
UPD: Well, i've reached out to EasyThreeD support on Ali, and a week short of three months of slow messaging and nagging from my side (they can keep you on unread for a while), they gave me these numbers for maximum Amps:

Z - 0.75A
X/Y/Extruder - 0.8A
So, according to that at least, maximum Vref should be:

Z - 1.2V
X/Y/Extruder - 1.28V

**Comment by schmttc** [comment]
Hi everyone, I've merged the K7 and K9 branches into main so the base code is the same, and the only thing that changes between models is the configuration files.
Config files are models separated in the config folder, and auto build a firmware to the config folder on push.

Please let me know if I've made a mess of the code and something needs to be changed or reverted

**Comment by schmttc** [comment]
@Rixxxi @JohnTheCoolingFan please see #28 as the place to address your ongoing layer shift issues. I've done a couple of small tests on speed and acceleration and haven't been able to reproduce.

Regarding my code merge in main, I can confirm the K7 firmware is working.

**Comment by schmttc** [comment]
I'm closing this issue as the original request to enable K9 functionality has been completed, many thanks @JohnTheCoolingFan for  sharing your work!
